name: Deploy
run-name: Deploy
on:
  workflow_call:
    secrets:
      repository_directory:
        required: true
jobs:
  build-and-deploy:
    name: Build and deploy Python package
    runs-on: self-hosted
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3
      - name: Install build requirements
        run: pip3 install -r src/requirements-build.txt
      - name: Create the distributable
        run: python3 -m build
      - name: Distribute the package
        shell: bash
        run: mv dist/*.tar.gz ${{ secrets.repository_directory }}/my-model/
